service: crypto-notification

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

  stage: prod
  region: us-east-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "sns:Publish"
          Resource: "arn:aws:sns:us-east-1:${self.custom.accountId}:${self.resources.Resources.CrpytoNotificationTopic.Properties.TopicName}"

custom:
  accountId: 859700905691

layers:
  nodeModules:
    path: layer

package:
  patterns:
    - "src/**"
    - "!layer/**"
    - "!node_modules/**"
    - "!package**"
    - "!README.md"

functions:
  deltachecker:
    handler: src/delta_checker.handler
    layers:
      - {Ref: NodeModulesLambdaLayer}
    events:
      - schedule: rate(10 minutes)
    environment:
      NOTIFICATION_TOPIC_ARN: "arn:aws:sns:us-east-1:${self.custom.accountId}:${self.resources.Resources.CrpytoNotificationTopic.Properties.TopicName}"

resources:
  Resources:
    CrpytoNotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: CrpytoNotificationTopic